name: dgp-snr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - pytest=5.4.*
  - black
  - mypy
  - git=2.26.*
  - matplotlib=3.1.*
  - numpy=1.18.*
  - pandas=1.0.*
  - requests=2.23.*
  - scikit-learn=0.22.*
  - scipy=1.4.*
  - tensorboard=1.15.*
  - tensorflow-gpu=1.15.0
  - tqdm=4.43.*
  - pip=20.0.*
  - pip:
      - -e .
      - gpflow==1.5.1
      - git+https://github.com/hughsalimbeni/bayesian_benchmarks.git
